name: lions_flutter
description: A Lions 307 Club App

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.13
  page_transition: ^2.0.9
  dropdown_button2: ^1.8.9
  intl: any
  http: ^0.13.5
  url_launcher: ^6.1.6
  flutter_slidable: ^2.0.0
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  pull_to_refresh: ^2.0.0
  crypto: ^3.0.2
  ntp: ^2.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  get: ^4.6.5
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  flag: ^6.0.0
  zoom_tap_animation: ^1.1.0
  flutter_markdown: ^0.6.14
  table_calendar: ^3.0.8
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dev: ^1.0.0
  flutter_secure_storage: ^8.0.0
  mocktail: ^0.3.0
  animations: ^2.0.7
  flutter_minimalist: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  test: ^1.24.1
  mockito: ^5.4.1
  lints: ^2.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
